version: 1
formatters:
  simple:
    format: '%(levelname)s:%(name)s:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
loggers:
  lyrics2music:
    handlers: [console]
    level: INFO
root:
  handlers: [console]
  level: INFO
